CREATE TABLE IF NOT EXISTS `members` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `username` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT INTO `members` (`id`, `name`, `username`) VALUES
(1, 'Lou Penland', 'loupenland'),
(2, 'Emil Spain', 'emilspain'),
(3, 'Palmer Honda', 'palmerhonda'),
(4, 'Long Flinn', 'longflinn'),
(5, 'Louisa Mans', 'louisamans'),
(6, 'Donte Baur', 'dontebaur'),
(7, 'Ervin Grisham', 'ervingrisham'),
(8, 'Maris Cort', 'mariscort'),
(9, 'Larry Dickison', 'larrydickison'),
(10, 'Elease Peevy', 'eleasepeevy'),
(11, 'Maranda Crook', 'marandacrook'),
(12, 'Jane Esser', 'janeesser'),
(13, 'Mathilde Orris', 'mathildeorris'),
(14, 'Tamera Sloss', 'tamerasloss'),
(15, 'Rolande Mudd', 'rolandemudd'),
(16, 'Lorita Angers', 'loritaangers'),
(17, 'Marquitta Lariviere', 'marquittalariviere'),
(18, 'Adalberto Sydow', 'adalbertosydow'),
(19, 'Wilfred Kirchoff', 'wilfredkirchoff'),
(20, 'Altagracia Kisling', 'altagraciakisling'),
(21, 'Clifton Opperman', 'cliftonopperman'),
(22, 'Augustine Rakes', 'augustinerakes'),
(23, 'Erick Hinerman', 'erickhinerman'),
(24, 'Coreen Bosh', 'coreenbosh'),
(25, 'Sherryl Scogin', 'sherrylscogin'),
(26, 'Cayla Woelfel', 'caylawoelfel'),
(27, 'Glennie Belknap', 'glenniebelknap'),
(28, 'Meridith Fahnestock', 'meridithfahnestock'),
(29, 'Collene Gudger', 'collenegudger'),
(30, 'Tyree Lisa', 'tyreelisa'),
(31, 'Robbyn Greathouse', 'robbyngreathouse'),
(32, 'Josue Lasky', 'josuelasky'),
(33, 'Etha Rushton', 'etharushton'),
(34, 'Vesta Valade', 'vestavalade'),
(35, 'Sharolyn Fedrick', 'sharolynfedrick'),
(36, 'Molly Drewes', 'mollydrewes'),
(37, 'Arielle Scheff', 'ariellescheff'),
(38, 'Jesenia Hauff', 'jeseniahauff'),
(39, 'Carylon Brion', 'carylonbrion'),
(40, 'Shantelle Banh', 'shantellebanh'),
(41, 'Romona Kumar', 'romonakumar'),
(42, 'Lottie Preciado', 'lottiepreciado'),
(43, 'Antonia Crisci', 'antoniacrisci'),
(44, 'Sumiko Yellowhair', 'sumikoyellowhair'),
(45, 'Racheal Gormley', 'rachealgormley'),
(46, 'Nicholas Speziale', 'nicholasspeziale'),
(47, 'Lino Kibbe', 'linokibbe'),
(48, 'Lexie Terhaar', 'lexieterhaar'),
(49, 'Hilton Klann', 'hiltonklann'),
(50, 'Christeen Keagle', 'christeenkeagle');